**데이터 인코딩**

- 레이블 인코딩(Label encoding)

In [3]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '세탁기', '에어컨', 'TV', '냉장고','믹서','믹서']

encoder = LabelEncoder()
encoder.fit(items)

labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 3 4 0 1 2 2]


In [4]:
print('인코딩 클래스 :', encoder.classes_)

인코딩 클래스 : ['TV' '냉장고' '믹서' '세탁기' '에어컨']


In [5]:
print('디코딩 원본 값 :', encoder.inverse_transform(labels))

디코딩 원본 값 : ['TV' '냉장고' '세탁기' '에어컨' 'TV' '냉장고' '믹서' '믹서']


- 원-핫 인코딩(One-Hot encoding)

In [10]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '세탁기', '에어컨', 'TV', '냉장고','믹서','믹서']

items = np.array(items).reshape(-1,1) 

oh_encode = OneHotEncoder()
oh_encode.fit(items)
oh_labels = oh_encode.transform(items)

print('원-핫 인코딩 변환값:\n', oh_labels.toarray())
print('원-핫 인코딩 데이터 차원:\n', oh_labels.shape)

원-핫 인코딩 변환값:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]
원-핫 인코딩 데이터 차원:
 (8, 5)


In [16]:
import pandas as pd

df = pd.DataFrame({'item': items.flatten()})

df

,item
0,TV
1,냉장고
2,세탁기
3,에어컨
4,TV
5,냉장고
6,믹서
7,믹서


In [21]:
ohe_df = pd.get_dummies(df).astype('int')
ohe_df

,item_TV,item_냉장고,item_믹서,item_세탁기,item_에어컨
0,1,0,0,0,0
1,0,1,0,0,0
2,0,0,0,1,0
3,0,0,0,0,1
4,1,0,0,0,0
5,0,1,0,0,0
6,0,0,1,0,0
7,0,0,1,0,0


**피처 스케일링과 정규화**

- StandardScaler

In [25]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()

iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print(iris_df.mean()) # 평균

print(iris_df.var()) # 분산

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [27]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled_df = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print(iris_scaled_df.mean()) # 평균
print(iris_scaled_df.var()) # 분산

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [28]:
scaler = StandardScaler()
scaler.fit_transform(iris_df)

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

- MinMaxScaler

In [29]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled_df = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print(iris_scaled_df.min()) # 최소값
print(iris_scaled_df.max()) # 최대값

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [34]:
scaler = MinMaxScaler()
scaler_df = scaler.fit_transform(iris_df)

print(scaler_df.min()) # 최소값
print(scaler_df.max()) # 최대값


0.0
1.0


- Scaler 를 이용하여 학습 데이터와 테스트 데이터에 fit(), transform(), fit_transform() 적용 시 유의 사항.

In [38]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

In [39]:
train_array, test_array

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]),
 array([[0],
        [1],
        [2],
        [3],
        [4],
        [5]]))

In [45]:
scaler = MinMaxScaler()

scaler.fit(train_array)

train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터 : ', np.round(train_array.reshape(-1), 2 ))
print('스케일링된 train_array 데이터 : ', np.round(train_scaled.reshape(-1), 2 ))

test_scaled = scaler.transform(test_array)

print('원본 test_array 데이터 : ', np.round(test_array.reshape(-1), 2 ))
print('스케일링된 test_array 데이터 : ', np.round(test_scaled.reshape(-1), 2 ))

원본 train_array 데이터 :  [ 0  1  2  3  4  5  6  7  8  9 10]
스케일링된 train_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 test_array 데이터 :  [0 1 2 3 4 5]
스케일링된 test_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5]


In [ ]:
scaler.fit(test_array)
test_scaled = scaler.transform(test_array)

print('원본 test_array 데이터 : ', np.round(test_array.reshape(-1), 2 ))
print('스케일링된 test_array 데이터 : ', np.round(test_scaled.reshape(-1), 2 ))

원본 test_array 데이터 :  [0 1 2 3 4 5]
스케일링된 test_array 데이터 :  [0.  0.2 0.4 0.6 0.8 1. ]
